### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir 'src/components'

### ISSUE THREAD

**Issue by HenryC-3** [Oak-Digital/types-4-strapi-2#11]
## Description

An error appears after running `npm  run types`

```bash
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, scandir 'src/components'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'src/components'
}
```

## System info

- Node.js v18.10.0
- Strapi v4.4.1

## Steps to reproduce

It can be reproduced in [t4s-2-reproduce](https://github.com/HenryC-3/strapi-ts-with_ts_interface_generator-demo/tree/t4s-2-reproduce) by running `npm run types`

**Comment by Alexnortung** [comment]
Thanks for sharing the issue and a reproduction repository. I will look into it.

**Comment by Alexnortung** [comment]
I think I know what is wrong, this won't be a problem when I get to create v1.

It seems that your project has no components, so a workaround would be to create a single component through strapi. Let me know if it works.

However of course this program should still work with no components in the src/ folder.

**Comment by HenryC-3** [comment]
Sorry for the late replay. It works.

Thank you.

**Comment by Alexnortung** [comment]
This should now work in version `0.3.1`
