### ISSUE TITLE
TS key should be optional when the field in strapi is not a required field

### ISSUE THREAD

**Issue by HenryC-3** [Oak-Digital/types-4-strapi-2#12]
## Description

Current t4s-2 generates required keys while `required field` option is not checked in strapi.

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/41246463/194259230-2f3e9210-d241-4836-992c-30d4f4d53dab.png">

## Expected output

- source:  Article `schema.json`

```json
{
  "kind": "collectionType",
  "collectionName": "articles",
  "info": {
    "singularName": "article",
    "pluralName": "articles",
    "displayName": "Article",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "title": {
      "type": "string"
    },
    "content": {
      "type": "richtext"
    },
    "author": {
      "type": "string"
    }
  }
}
```
- expected output: `Article.ts`
```ts
export interface IArticle {
  id: number;
  attributes: {
    title?: string;
    content?: string;
    author?: string;
  };
}
```
- current output
```ts
export interface IArticle {
  id: number;
  attributes: {
    title: string;
    content: string;
    author: string;
  };
}
```

**Comment by HenryC-3** [comment]
And  I notice that the interfaces name generated from user defined content type always starts with letter I, is this designed on purpose?

**Comment by Alexnortung** [comment]
> And I notice that the interfaces name generated from user defined content type always starts with letter I, is this designed on purpose?

This is just a default and can be changed to your liking. It is also a goal of this project to be very configurable.
You can change it with the `--prefix` option.

---

As for the original question:
Strapi still sends the field, so it should not be undefined, but you are right, it should be nullable.

However there is another problem, if a content type is updated from not required to required, the interface would now say that it could not be nullable, however it can still be the case that the user hasn't updated the content and it can still be null. I think there should be a "paranoid" option as well.
